# Add/Overwrite new configuration options
# See: https://github.com/bolt/core/commit/7f1347a21d99c06dae157204ebadd4cbabf94b55
# See: https://github.com/bolt/core/commit/2c0f4b18c576927a28f0db6c73732d2dc63b6d65
# See: https://github.com/bolt/core/commit/9aebe9c472e94a0eed64eb4643f82c7057d614b4

file: bolt/config.yaml
since: 5.2.0

add:
    caching:
        list_format: false
    maximum_listing_select: 50000
    ajaxy_saving: false
