name: Unit Tests Checks

on:
    pull_request:

jobs:
    unittests:
        strategy:
            matrix:
                php-version: [ '7.2', '8.0' ]
            fail-fast: false
        name: PHPUnit 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: shivammathur/setup-php@v2
              with:
                # test the lowest version, to make sure checks pass on it
                php-version: ${{ matrix.php-version }}
                extensions: json, mbstring, pdo, curl, pdo_sqlite
                coverage: none
            - name: Install composer dependencies
              uses: php-actions/composer@v6
              with:
                  php_version: ${{ matrix.php-version }}
            - name: run PHP Unit
              run: ./vendor/bin/phpunit
